### ISSUE TITLE
wrong play input stops the script from running

### ISSUE THREAD

**Issue by HariSeldon0fe** [mjsalerno/UnoBot#20] opened 2016-06-23 13:14 UTC
found a bug when someone gives a wrong input the script stops accepting input

`[main] INFO org.pircbotx.InputParser - :ryelle!Ryelle@Ryelle.admin.IkariamCom PRIVMSG ##uno :!play yr
[listenerPool0-thread1] ERROR org.pircbotx.hooks.managers.ThreadedListenerManager - Exception encountered when executing event MessageEvent(channel=Channel
(name=##uno, channelId=5223f51d-fb26-4342-ad63-60e6188a9221, dao=org.pircbotx.UserChannelDao@1990ca, bot=Version{mIRC v7.32 Khaled Mardam-Bey} Connected{tr
ue} Server{znc.centravi.org} Port{9001} Password{uno:KXghTgVA}, output=org.pircbotx.Channel$1@70f11d, mode=+ntz, topic=Uno Game Channel! Use !uno to sta
rt the game, if there are any issues PM Hari_Seldon., topicTimestamp=1466671926000, createTimestamp=1466284882, topicSetter=Hari_Seldon, moderated=false, n
oExternalMessages=true, inviteOnly=false, secret=false, channelPrivate=false, topicProtection=true, channelLimit=-1, channelKey=null, modeStale=false, mode
Latch=null), user=User(bot=Version{mIRC v7.32 Khaled Mardam-Bey} Connected{true} Server{znc.centravi.org} Port{9001} Password{CENSORED}, dao=org.pircbo
tx.UserChannelDao@1990ca, userId=f3e4a6e5-5f20-4048-89cf-3ce5a8ee737d, output=org.pircbotx.User$1@e5cd19, nick=Hari_Seldon, realName=Hari_Seldon, login=Har
i_Seldo, hostmask=Hari_Seldon.user.OnlineGamesNet, awayMessage=null, ircop=false, server=*.OnlineGamesNet.net, hops=3), message=!uno +e +a) on listener com
.mjsalerno.unobot.UnoBot@a6a5dc
java.lang.ArrayIndexOutOfBoundsException: 2
       at com.mjsalerno.unobot.UnoBot.onMessage(UnoBot.java:718)
       at org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:63)
       at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:119)
       at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:115)
       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)
[main] INFO org.pircbotx.InputParser - :ryelle!Ryelle@Ryelle.admin.IkariamCom PRIVMSG ##uno :!play y r
[main] INFO org.pircbotx.InputParser - :ryelle!Ryelle@Ryelle.admin.IkariamCom PRIVMSG ##uno :hm
[main] INFO org.pircbotx.InputParser - :ryelle!Ryelle@Ryelle.admin.IkariamCom PRIVMSG ##uno :!play y r`

**Comment by mjsalerno** [comment] 2016-06-23 13:36
can you give me the steps to reproduce this error?

**Comment by HariSeldon0fe** [comment] 2016-06-23 13:39
sure start a game and have a player type !play y6 instead of !play y 6 or anything like that

**Comment by mjsalerno** [comment] 2016-06-23 15:57
Ok this should be fixed now. Also you should change your server's password since it is in your pasted stacktrace.

**Closed** 2016-06-25 18:26 UTC
